CREATE TABLE PESSOAS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DDD TINYINT,
    TELEFONE CHAR(9) UNIQUE,
    CARGO ENUM ('atendente', 'entregador', 'gerente','cliente'),
    CPF CHAR(11),    
    ENDERECOSID INTEGER,    
    FOREIGN KEY (ENDERECOSID) REFERENCES ENDERECOS(ID)
);

CREATE TABLE BAIRROS(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100),
TAXA FLOAT
);

CREATE TABLE ENDERECOS(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
RUA VARCHAR(40) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
COMPLEMENTO VARCHAR(200) NOT NULL,
BAIRROSID INTEGER,
FOREIGN KEY (BAIRROSID) REFERENCES BAIRROS(ID)
);

CREATE TABLE PEDIDOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	OBSERVACAO VARCHAR(300), /**/
	PRECOTOTAL FLOAT,
	HORARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PESSOASID INTEGER,
    ENDERECOSID INTEGER,
    FOREIGN KEY (PESSOASID) REFERENCES PESSOAS(ID),
    FOREIGN KEY (ENDERECOSID) REFERENCES ENDERECOS(ID)
);

CREATE TABLE PRODUTOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO FLOAT,
    CATEGORIA ENUM ('pizza', 'bebidas', 'outros'),
    DESCRICAO VARCHAR(300),
    ESTOQUE FLOAT
);

CREATE TABLE SABORES(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (100) NOT NULL,
CATEGORIAID INTEGER,
FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE CATEGORIA(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
PRECO0 FLOAT,
PRECO1 FLOAT,
PRECO2 FLOAT,
PRECO3 FLOAT,
PRECO4 FLOAT
);

Create TABLE PIZZAS(
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
SABOR1ID INTEGER,
SABOR2ID INTEGER,
BORDA ENUM ('catupiry', 'cheddar', 'sem borda'),
TAMANHO smallint,
FOREIGN KEY (SABOR1ID) REFERENCES SABORES(ID),
FOREIGN KEY (SABOR2ID) REFERENCES SABORES(ID)
);

Create Table INGREDIENTES(
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100),
DESCRICAO VARCHAR(100)
);

/* Relaçoes*/
CREATE TABLE PEDIDOS_PRODUTOS(
PEDIDOSID INTEGER,
PRODUTOSID INTEGER,
PIZZASID INTEGER,
QUANTIDADE TINYINT,
FOREIGN KEY (PEDIDOSID) REFERENCES PEDIDOS(ID),
FOREIGN KEY (PRODUTOSID) REFERENCES PRODUTOS(ID),
FOREIGN KEY (PIZZASID) REFERENCES PIZZAS(ID)
);

CREATE TABLE INGREDIENTES_PRODUTOS(
INGREDIENTESID INTEGER,
PRODUTOSID INTEGER,
QUANTIDADE INTEGER,
FOREIGN KEY (PRODUTOSID) REFERENCES PRODUTOS(ID),
FOREIGN KEY (INGREDIENTESID) REFERENCES INGREDIENTES(ID)
);

CREATE TABLE INGREDIENTES_SABORES(
INGREDIENTESID INTEGER,
SABORESID INTEGER,
QUANTIDADE INTEGER,
FOREIGN KEY (SABORESID) REFERENCES SABORES(ID),
FOREIGN KEY (INGREDIENTESID) REFERENCES INGREDIENTES(ID)
);