/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TCD.GUI;

import TCD.Classes.Bairro;
import TCD.DB.BairroDao;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Declaração da classe da Tela de Bairro
 * 
 * @author Marcos Dias
 * @author Rafael Paranhos
 * @author Thiago Evangelista
 * @author Wellington Junio
 */
public class TelaBairro extends javax.swing.JFrame {

    /** Listas de bairros*/
    List<Bairro> bairros;
    
     /** Creates new form TelaBairro */
    public TelaBairro() {
        initComponents();
        buscar();
    }
    
    /** Busca todos os bairros no banco de dados */
    public void buscar(){
        bairros = new BairroDao().localizarTodos();
        atualizarLista();
    }
    
    /**
     * Busca os bairros com o filtro de nome
     * @param nome do bairro para filtro
     */
    public void buscar(String nome){
        bairros = new BairroDao().buscarPorNome(nome);
        atualizarLista();
    }
    
    /**
     * Atualiza a jlist com a lista de bairros
     */
    public void atualizarLista(){
        DefaultListModel model = new DefaultListModel();
        bairros.forEach(b->{
        model.addElement(b.toString());
        });
        bairroList.setModel(model);
    }
    
    /**
     * Atribui valores as text box
     * @param bairro selecionado
     */
    public void atribuirValores(Bairro bairro){
        nomeTF.setText(bairro.getNome());
        taxaTF.setText(Float.toString(bairro.getTaxa()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taxaTF = new javax.swing.JTextField();
        nomeTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bairroList = new javax.swing.JList<>();
        salvarBTN = new javax.swing.JButton();
        excluirBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buscarTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bairros"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taxaTF.setBackground(new java.awt.Color(240, 240, 240));
        taxaTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taxaTF.setText("Taxa Entrega");
        taxaTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        taxaTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taxaTFMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                taxaTFMousePressed(evt);
            }
        });
        taxaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taxaTFKeyTyped(evt);
            }
        });
        jPanel1.add(taxaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 138, 149, -1));

        nomeTF.setBackground(new java.awt.Color(240, 240, 240));
        nomeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomeTF.setText("Nome");
        nomeTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nomeTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nomeTFMousePressed(evt);
            }
        });
        nomeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTFActionPerformed(evt);
            }
        });
        jPanel1.add(nomeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 111, 149, -1));

        jScrollPane1.setOpaque(false);

        bairroList.setBackground(new java.awt.Color(240, 240, 240));
        bairroList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Bairros"));
        bairroList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        bairroList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bairroListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(bairroList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 111, 307, 220));

        salvarBTN.setBackground(new java.awt.Color(255, 255, 255));
        salvarBTN.setText("Salvar");
        salvarBTN.setOpaque(false);
        salvarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(salvarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 343, -1, -1));

        excluirBTN.setBackground(new java.awt.Color(255, 255, 255));
        excluirBTN.setText("Excluir");
        excluirBTN.setOpaque(false);
        excluirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBTNActionPerformed(evt);
            }
        });
        jPanel1.add(excluirBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 343, -1, -1));

        jLabel1.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, -1, -1));

        buscarTF.setBackground(new java.awt.Color(240, 240, 240));
        buscarTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buscarTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        buscarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTFActionPerformed(evt);
            }
        });
        buscarTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarTFKeyTyped(evt);
            }
        });
        jPanel1.add(buscarTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 36, 159, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Buscar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 36, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpar Seleçao");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Events">  
    private void nomeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTFActionPerformed
 
    }//GEN-LAST:event_nomeTFActionPerformed

    private void taxaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxaTFKeyTyped
        if("Taxa Entrega".equals(taxaTF.getText()))
            taxaTF.setText("");
        
         String caracteresDisponiveis = "0123456789.";

        if (!caracteresDisponiveis.contains(evt.getKeyChar() + "") || taxaTF.getText().length() >= 8) 
            evt.consume();
        
        
    }//GEN-LAST:event_taxaTFKeyTyped

    private void taxaTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taxaTFMousePressed
        if("Taxa Entrega".equals(taxaTF.getText()))
            taxaTF.setText("");
    }//GEN-LAST:event_taxaTFMousePressed

    private void taxaTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taxaTFMouseClicked

    }//GEN-LAST:event_taxaTFMouseClicked

    private void nomeTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeTFMousePressed
        if("Nome".equals(nomeTF.getText()))
            nomeTF.setText("");
    }//GEN-LAST:event_nomeTFMousePressed

    private void salvarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTNActionPerformed
        Bairro bairro;
        if(bairroList.isSelectionEmpty())
            bairro = new Bairro();
        else
            bairro = bairros.get(bairroList.getSelectedIndex());
        
        bairro.setNome(nomeTF.getText());
        bairro.setTaxa(Float.parseFloat(taxaTF.getText()));
        bairro.setId(new BairroDao().buscarExistente(bairro));
              
        bairro.setId(new BairroDao().salvar(bairro));
        
        buscar(buscarTF.getText());
    }//GEN-LAST:event_salvarBTNActionPerformed

    private void buscarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTFActionPerformed

    private void bairroListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bairroListMousePressed
        if(bairroList.isSelectionEmpty())
            return;
        atribuirValores(bairros.get(bairroList.getSelectedIndex()));
        
    }//GEN-LAST:event_bairroListMousePressed

    private void buscarTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTFKeyTyped
        String text = buscarTF.getText();
        char evtText = evt.getKeyChar();
        if(evtText != '\b' && evtText != '\n'){
            text = text + evtText;
        }
        buscar(text);
    }//GEN-LAST:event_buscarTFKeyTyped

    private void excluirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBTNActionPerformed
        if(bairroList.isSelectionEmpty())
            return;
        new BairroDao().excluirBairro(bairros.get(bairroList.getSelectedIndex()));
        buscar();
    }//GEN-LAST:event_excluirBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bairroList.clearSelection();
       
    }//GEN-LAST:event_jButton1ActionPerformed
// </editor-fold> 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> bairroList;
    private javax.swing.JTextField buscarTF;
    private javax.swing.JButton excluirBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JButton salvarBTN;
    private javax.swing.JTextField taxaTF;
    // End of variables declaration//GEN-END:variables
}
