/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TCD.GUI;


import TCD.Classes.Ingrediente;
import TCD.DB.IngredienteDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Declaração da classe da Tela de Ingrediente
 * 
 * @author Marcos Dias
 * @author Rafael Paranhos
 * @author Thiago Evangelista
 * @author Wellington Junio
 */
public class TelaIngrediente extends javax.swing.JFrame {

    /** Lista de ingredientes */
    private List<Ingrediente> ingredientes;
    
    /**
     * Creates new form TelaIngrediente
     */
    public TelaIngrediente() {
        ingredientes = new ArrayList<>();
        initComponents();
        buscarIngredientes();
    }
    
    /**
     * Busca todos os ingredientes
     */
    public void buscarIngredientes(){
        ingredientes = new IngredienteDao().localizarTodos();
        atualizarLista();
    }
    
    /**
     * Busca os ingredientes pelo filtro do nome
     * @param nome para filtro
     */
    public void buscarIngredientes(String nome){
        ingredientes = new IngredienteDao().buscarPorNome(nome);
        atualizarLista();
    }
    
    /**
     * Atualiza a jlist com base na busca
     */
    public void atualizarLista(){
        DefaultListModel model = new DefaultListModel();
        ingredientes.forEach(i->{ 
        model.addElement(i);});
        ingredientsList.setModel(model);
        ingredientsList.clearSelection();
    }
    
    /**
     * Limpa as text boxes
     */
    public void limparCampos(){
        nomeTF.setText("");
        descricaoTF.setText("");
        atualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTF = new javax.swing.JTextField();
        descricaoTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientsList = new javax.swing.JList<>();
        salvarBTN = new javax.swing.JButton();
        LimparBTN = new javax.swing.JButton();
        excluirBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        nomeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Descricao:");

        jLabel2.setText("Nome:");

        ingredientsList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Ingredientes"));
        ingredientsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ingredientsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingredientsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ingredientsList);

        salvarBTN.setText("Salvar");
        salvarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTNActionPerformed(evt);
            }
        });

        LimparBTN.setText("Limpar Seleção");
        LimparBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparBTNActionPerformed(evt);
            }
        });

        excluirBTN.setText("Excluir");
        excluirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBTNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Buscar:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel5.setText("_________________________________________________________________________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descricaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(salvarBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(excluirBTN)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LimparBTN)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descricaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvarBTN)
                            .addComponent(excluirBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LimparBTN)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Events">
    private void nomeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTFActionPerformed

    private void salvarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTNActionPerformed
        Ingrediente ingrediente; 
        if(ingredientsList.getSelectedValue() == null)
            ingrediente = new Ingrediente();
                  
         else
             ingrediente = ingredientes.get(ingredientsList.getSelectedIndex());   
         
        ingrediente.setNome(nomeTF.getText());
        ingrediente.setDescricao(descricaoTF.getText());


        ingrediente.setId(new IngredienteDao().salvar(ingrediente));
        buscarIngredientes();
        limparCampos();      
        
    }//GEN-LAST:event_salvarBTNActionPerformed

    private void LimparBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparBTNActionPerformed
       
        ingredientsList.clearSelection();
        salvarBTN.setText("Salvar");
    }//GEN-LAST:event_LimparBTNActionPerformed

    private void ingredientsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredientsListMouseClicked
        if(ingredientsList.getSelectedValue() == null)
            return;
        else{
            Ingrediente ingrediente = ingredientes.get(ingredientsList.getSelectedIndex());  
            nomeTF.setText(ingrediente.getNome());
            descricaoTF.setText(ingrediente.getDescricao());
        
        }
    }//GEN-LAST:event_ingredientsListMouseClicked

    private void excluirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBTNActionPerformed
        if(ingredientsList.getSelectedValue() == null)
            return;
        else{
            Ingrediente ingrediente = ingredientes.get(ingredientsList.getSelectedIndex());
            new IngredienteDao().excluirIngredientes(ingrediente);
        }
        buscarIngredientes();
        limparCampos();
    }//GEN-LAST:event_excluirBTNActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        buscarIngredientes(jTextField1.getText() + evt.getKeyChar());
    }//GEN-LAST:event_jTextField1KeyTyped
    // </editor-fold>
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimparBTN;
    private javax.swing.JTextField descricaoTF;
    private javax.swing.JButton excluirBTN;
    private javax.swing.JList<String> ingredientsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JButton salvarBTN;
    // End of variables declaration//GEN-END:variables
}
