/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TCD.GUI;

import TCD.Classes.Bairro;
import TCD.Classes.Endereco;
import TCD.Classes.Funcionario;
import TCD.DB.BairroDao;
import TCD.DB.EnderecoDao;
import TCD.DB.FuncionarioDao;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Declaração da classe da Tela de Funcionario
 * 
 * @author Marcos Dias
 * @author Rafael Paranhos
 * @author Thiago Evangelista
 * @author Wellington Junio
 */
public class TelaBuscarFuncionario extends javax.swing.JFrame {

    /** Vetor com nome dos funcionarios */
    private String[] str;
    /** Lista de funcionarios */
    List<Funcionario> funcionarios;
    /** Lista de bairros */
    List<Bairro> bairrosList;
    
    /**
     * Creates new form TelaBuscarFuncionario
     */
    public TelaBuscarFuncionario() {
        initComponents();
        buscar();
        pesquisaBairroList.setVisible(false);
    }
    
    /**
     * Limpa os campos das text boxes
     */
    public void limparCampos(){
        nomeTF.setText("");
        dddTF.setText("");
        telefoneTF.setText("");
        cpfTF.setText("");
        cargoCB.setSelectedItem("");
        ruaTF.setText("");
        bairroTF.setText("");
        numeroTF.setText("");
        complementoTF.setText("");
    }
    
    /**
     * Atualiza a jlist de funcionarios
     */
    public void atualizarLista(){
        DefaultListModel model = new DefaultListModel();
        funcionarios.forEach(c->{
        model.addElement(c.toString());});
        jList1.setModel(model);
    }
    
    /**
     * Preenche os campos das text boxes com os valores de funcionario
     * @param func funcionario selecionado
     */
    public void preencherCampos(Funcionario func){
        nomeTF.setText(func.getNome());
        telefoneTF.setText(func.getTelefone());
        dddTF.setText(func.getDDD());
        cpfTF.setText(func.getCpf());
        cargoCB.setSelectedItem(func.getCargo());
        if(func.getEndereco() == null){
            ruaTF.setText("");        
            numeroTF.setText("");
            complementoTF.setText("");
            bairroTF.setText("");
        }
        else{
            ruaTF.setText(func.getEndereco().getRua());        
            numeroTF.setText(func.getEndereco().getNumero());
            complementoTF.setText(func.getEndereco().getComplemento());
            if(func.getEndereco().getBairro() == null)
                bairroTF.setText("");
            else
                bairroTF.setText(func.getEndereco().getBairro().getNome());
        }
        
    }
    
    /**
     * Busca todos os funcionarios no banco de dados
     */
    public void buscar(){
        funcionarios = new FuncionarioDao().localizarTodos();
        atualizarLista();
    }
    
    /**
     * Busca os funcionarios com base no filtro de nome e telefone
     * @param text nome ou telefone 
     */
    public void buscar(String text){
        funcionarios =  new FuncionarioDao().buscarPorNomeTelefone(text);
        atualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisaBairroList = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        buscarTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        telefoneTF = new javax.swing.JTextField();
        dddTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ruaTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numeroTF = new javax.swing.JTextField();
        complementoTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        atualizarBTN = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cpfTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cargoCB = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        limparBTN = new javax.swing.JButton();
        bairroTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesquisaBairroList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pesquisaBairroList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisaBairroListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pesquisaBairroListMousePressed(evt);
            }
        });
        getContentPane().add(pesquisaBairroList, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 270, 150, 80));

        jLabel8.setText("Buscar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, -1, -1));

        buscarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTFActionPerformed(evt);
            }
        });
        buscarTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarTFKeyTyped(evt);
            }
        });
        getContentPane().add(buscarTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, 130, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        nomeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTFActionPerformed(evt);
            }
        });
        nomeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeTFKeyTyped(evt);
            }
        });
        getContentPane().add(nomeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 122, 150, -1));

        jLabel1.setText("______________________________________________________________________________________________________");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 659, -1));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 122, 350, 240));

        telefoneTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefoneTFKeyTyped(evt);
            }
        });
        getContentPane().add(telefoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 153, 114, -1));

        dddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dddTFActionPerformed(evt);
            }
        });
        dddTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dddTFKeyTyped(evt);
            }
        });
        getContentPane().add(dddTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 153, 30, -1));

        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, -1, -1));

        jLabel4.setText("Bairro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, -1, -1));

        jLabel5.setText("Rua");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, -1, -1));

        ruaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ruaTFKeyTyped(evt);
            }
        });
        getContentPane().add(ruaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 280, 150, -1));

        jLabel6.setText("Numero");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 312, -1, -1));
        getContentPane().add(numeroTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 309, 150, -1));
        getContentPane().add(complementoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 347, 150, -1));

        jLabel7.setText("Complemento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        atualizarBTN.setText("Salvar");
        atualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel9.setText("Cpf");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, -1, -1));

        cpfTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTFActionPerformed(evt);
            }
        });
        cpfTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpfTFKeyTyped(evt);
            }
        });
        getContentPane().add(cpfTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 184, 150, -1));

        jLabel10.setText("Cargo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, -1, -1));

        cargoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "atendente", "entregador", "gerente" }));
        getContentPane().add(cargoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 215, 150, -1));

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        limparBTN.setText("Limpar Seleção");
        limparBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBTNActionPerformed(evt);
            }
        });
        getContentPane().add(limparBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        bairroTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroTFActionPerformed(evt);
            }
        });
        bairroTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bairroTFKeyTyped(evt);
            }
        });
        getContentPane().add(bairroTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 250, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTFActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Events">
    private void buscarTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTFKeyTyped

        String text = buscarTF.getText();
        char evtText = evt.getKeyChar();
        if(evtText != '\b' && evtText != '\n'){
            text = text + evtText;
        }

        funcionarios =  new FuncionarioDao().buscarPorNomeTelefone(text);
        str = new String[funcionarios.size()];
        for(int i = 0; i<funcionarios.size(); i++){
            str[i] = funcionarios.get(i).getNome().concat("  (" + funcionarios.get(i).getDDD() + ") "+ funcionarios.get(i).getTelefone());
        }
        jList1.setListData(str);

    }//GEN-LAST:event_buscarTFKeyTyped

    private void nomeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTFActionPerformed

    private void nomeTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTFKeyTyped

    }//GEN-LAST:event_nomeTFKeyTyped

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if(jList1.isSelectionEmpty())
            return ;
        Funcionario func = funcionarios.get(jList1.getSelectedIndex());
        preencherCampos(func);        
        atualizarBTN.setText("Atualizar");
    }//GEN-LAST:event_jList1MouseClicked

    private void dddTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dddTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dddTFActionPerformed

    private void atualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBTNActionPerformed
        Funcionario func;
        if(!jList1.isSelectionEmpty())
            func = funcionarios.get(jList1.getSelectedIndex());
        else
            func = new Funcionario();
        
        
        if(func.getEndereco()== null)
            func.setEndereco(new Endereco());
        if(pesquisaBairroList.getSelectedValue() == bairroTF.getText()){
            func.getEndereco().setBairro(bairrosList.get(pesquisaBairroList.getSelectedIndex()));
        }else{
            Bairro bairroTemp = new Bairro();
            bairroTemp.setNome(bairroTF.getText());
            bairroTemp.setId(new BairroDao().buscarExistente(bairroTemp));
            
            if(bairroTemp.getId() != null)
                func.getEndereco().setBairro(new BairroDao().localizarPorId(bairroTemp.getId()));
            else
                func.getEndereco().setBairro(bairroTemp);
                func.getEndereco().getBairro().setTaxa(0F);
                
            
        func.getEndereco().getBairro().setId(new BairroDao().salvar(func.getEndereco().getBairro()));    
        
        func.getEndereco().setRua(ruaTF.getText());
        func.getEndereco().setNumero(numeroTF.getText());
        func.getEndereco().setComplemento(complementoTF.getText());
        
        func.getEndereco().setId(new EnderecoDao().salvar(func.getEndereco()));
        
        func.setNome(nomeTF.getText());
        func.setDDD(dddTF.getText());
        func.setTelefone(telefoneTF.getText());
        func.setCpf(cpfTF.getText().replace("-", ""));
        func.setCargo((String)cargoCB.getSelectedItem());

        new FuncionarioDao().salvar(func);
        }
        buscar(buscarTF.getText());
        
        limparCampos();
    }//GEN-LAST:event_atualizarBTNActionPerformed

    private void cpfTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jList1.getSelectedValue() != null){
            Funcionario func = funcionarios.get(jList1.getSelectedIndex());
            new FuncionarioDao().excluir(func);
            if(func.getEndereco() != null)
                if(new EnderecoDao().verificarUso(func.getEndereco()) == false)
                    new EnderecoDao().excluir(func.getEndereco());
            buscar();
            limparCampos();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cpfTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfTFKeyTyped
        String caracteresDisponiveis = "0123456789";
        
        if (!caracteresDisponiveis.contains(evt.getKeyChar() + "") || cpfTF.getText().length() >= 12) 
            evt.consume();
        else{
            String text = cpfTF.getText()+ evt.getKeyChar();
            if(text.length() == 9){
                cpfTF.setText(text + "-");
                evt.consume();
            }
        }
            
    }//GEN-LAST:event_cpfTFKeyTyped

    private void telefoneTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneTFKeyTyped
        String caracteresDisponiveis = "0123456789";

        if (!caracteresDisponiveis.contains(evt.getKeyChar() + "") || telefoneTF.getText().length() >= 9) 
            evt.consume();
    }//GEN-LAST:event_telefoneTFKeyTyped

    private void dddTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dddTFKeyTyped
        String caracteresDisponiveis = "0123456789";

        if (!caracteresDisponiveis.contains(evt.getKeyChar() + "") || dddTF.getText().length() >= 2) 
            evt.consume();
    }//GEN-LAST:event_dddTFKeyTyped

    private void limparBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBTNActionPerformed
        jList1.clearSelection();
        atualizarBTN.setText("Salvar");
        limparCampos();
        buscar();
    }//GEN-LAST:event_limparBTNActionPerformed

    private void pesquisaBairroListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaBairroListMouseExited
        pesquisaBairroList.setVisible(false);
    }//GEN-LAST:event_pesquisaBairroListMouseExited

    private void pesquisaBairroListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaBairroListMousePressed
        if(pesquisaBairroList.getSelectedValue() != null){
            bairroTF.setText(bairrosList.get(pesquisaBairroList.getSelectedIndex()).getNome());
            pesquisaBairroList.setVisible(false);
            
        }
    }//GEN-LAST:event_pesquisaBairroListMousePressed

    private void bairroTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroTFActionPerformed

    private void bairroTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bairroTFKeyTyped

        String text = bairroTF.getText();
        char evtText = evt.getKeyChar();
        if (evtText != '\b' && evtText != '\n') {
            text = text + evtText;
        }
        DefaultListModel model = new DefaultListModel();
        bairrosList = new BairroDao().buscarPorNome(text);
        bairrosList.forEach(b -> {
            model.addElement(b.getNome());
        });

        pesquisaBairroList.setVisible(true);
        pesquisaBairroList.setModel(model);
        if (text.length() == 0 || bairrosList.size() == 0) {
            pesquisaBairroList.setVisible(false);
        }
      

        if(bairrosList.size() == 1 && (bairrosList.get(0).getNome() == null ? text == null : bairrosList.get(0).getNome().equals(text))){
            pesquisaBairroList.setSelectedIndex(0);
            
        }

    }//GEN-LAST:event_bairroTFKeyTyped

    private void ruaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ruaTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaTFKeyTyped
// </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBTN;
    private javax.swing.JTextField bairroTF;
    private javax.swing.JTextField buscarTF;
    private javax.swing.JComboBox<String> cargoCB;
    private javax.swing.JTextField complementoTF;
    private javax.swing.JTextField cpfTF;
    private javax.swing.JTextField dddTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparBTN;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JTextField numeroTF;
    private javax.swing.JList<String> pesquisaBairroList;
    private javax.swing.JTextField ruaTF;
    private javax.swing.JTextField telefoneTF;
    // End of variables declaration//GEN-END:variables
}
