/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TCD.GUI;

import TCD.Classes.Bairro;
import TCD.Classes.Cliente;
import TCD.Classes.Endereco;
import TCD.DB.BairroDao;
import TCD.DB.ClienteDao;
import TCD.DB.EnderecoDao;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Declaração da classe da Tela de Bairro
 * 
 * @author Marcos Dias
 * @author Rafael Paranhos
 * @author Thiago Evangelista
 * @author Wellington Junio
 */
public class TelaBuscarCliente extends javax.swing.JFrame {
   
    /** Lista de clientes */
    List<Cliente> clientes;
    /** Lista de bairros */ 
    List<Bairro> bairrosList;
    
    /**
     * Creates new form TelaBuscarCliente
     */
    public TelaBuscarCliente() {
        initComponents();
        buscar();
        pesquisaBairroList.setVisible(false);
    }
    
    /** 
     * Limpa os campos de text box 
     */
    public void limparCampos(){
        nomeTF.setText("");
        telefoneTF.setText("");
        dddTF.setText("");
        ruaTF.setText("");
        bairroTF.setText("");
        numeroTF.setText("");
        complementoTF.setText("");
    }
    
    /**
     * Atualiza a jlist de clientes
     */
    public void atualizarLista(){
        DefaultListModel model = new DefaultListModel();
        clientes.forEach(c->{
        model.addElement(c.toString());});
        jList1.setModel(model);
        jList1.clearSelection();
    }
    
    /**
     * Preenche as text boxes com o cliente selecionado
     * @param c cliente selecionado
     */
    public void preencherCampos(Cliente c){
        nomeTF.setText(c.getNome());
        telefoneTF.setText(c.getTelefone());
        dddTF.setText(c.getDDD());
        if(c.getEndereco() == null){
            ruaTF.setText("");        
            numeroTF.setText("");
            complementoTF.setText("");
            bairroTF.setText("");
        }
        else{
            ruaTF.setText(c.getEndereco().getRua());        
            numeroTF.setText(c.getEndereco().getNumero());
            complementoTF.setText(c.getEndereco().getComplemento());
            if(c.getEndereco().getBairro() == null)
                bairroTF.setText("");
            else
                bairroTF.setText(c.getEndereco().getBairro().getNome());
        }
    }
    
    /**
     * Busca todos os clientes
     */
    public void buscar(){
        clientes = new ClienteDao().localizarTodos();
        atualizarLista();
    }
    
    /**
     * Busca o cliente com o filtro de nome ou telefone
     * @param text nome ou telefone
     */
    public void buscar(String text){
        clientes =  new ClienteDao().buscarPorNomeTelefone(text);
        atualizarLista();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dddTF = new javax.swing.JTextField();
        telefoneTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ruaTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numeroTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        complementoTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buscarTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        atualizarBTN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        limparBTN = new javax.swing.JButton();
        pesquisaBairroList = new javax.swing.JList<>();
        bairroTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        nomeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTFActionPerformed(evt);
            }
        });
        nomeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeTFKeyTyped(evt);
            }
        });
        getContentPane().add(nomeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 122, 150, -1));

        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, -1, -1));

        dddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dddTFActionPerformed(evt);
            }
        });
        dddTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dddTFKeyTyped(evt);
            }
        });
        getContentPane().add(dddTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 153, 30, -1));

        telefoneTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefoneTFKeyTyped(evt);
            }
        });
        getContentPane().add(telefoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 153, 114, -1));

        jLabel4.setText("Bairro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, -1, -1));

        jLabel5.setText("Rua");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 247, -1, -1));
        getContentPane().add(ruaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 244, 150, -1));

        jLabel6.setText("Numero");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 291, -1, -1));
        getContentPane().add(numeroTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 288, 150, -1));

        jLabel7.setText("Complemento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 334, -1, -1));
        getContentPane().add(complementoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 331, 150, -1));

        jLabel1.setText("______________________________________________________________________________________________________");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 615, -1));

        jLabel8.setText("Buscar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, -1, -1));

        buscarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTFActionPerformed(evt);
            }
        });
        buscarTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarTFKeyTyped(evt);
            }
        });
        getContentPane().add(buscarTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, 130, -1));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 122, 353, 229));

        atualizarBTN.setText("Salvar");
        atualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        limparBTN.setText("Limpar Seleção");
        limparBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBTNActionPerformed(evt);
            }
        });
        getContentPane().add(limparBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 357, -1, -1));

        pesquisaBairroList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pesquisaBairroList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisaBairroListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pesquisaBairroListMousePressed(evt);
            }
        });
        getContentPane().add(pesquisaBairroList, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 220, 150, 80));

        bairroTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroTFActionPerformed(evt);
            }
        });
        bairroTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bairroTFKeyTyped(evt);
            }
        });
        getContentPane().add(bairroTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 200, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Events">
    private void nomeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTFActionPerformed

    private void dddTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dddTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dddTFActionPerformed

    private void nomeTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTFKeyTyped
        
    }//GEN-LAST:event_nomeTFKeyTyped

    private void buscarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTFActionPerformed

    private void buscarTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTFKeyTyped
        
        String text = buscarTF.getText();
        char evtText = evt.getKeyChar();
        if(evtText != '\b' && evtText != '\n'){
            text = text + evtText;
        }
        buscar(text);
        
        
   
            
    }//GEN-LAST:event_buscarTFKeyTyped

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if(jList1.isSelectionEmpty())
            return;
        else{
            Cliente c = clientes.get(jList1.getSelectedIndex());
            preencherCampos(c);
            atualizarBTN.setText("Atualizar");
        }
        
       
        
    }//GEN-LAST:event_jList1MouseClicked

    private void atualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBTNActionPerformed
        Cliente c;
        if(!jList1.isSelectionEmpty())
            c = clientes.get(jList1.getSelectedIndex());
        else
            c = new Cliente();
        
        
        if(c.getEndereco()==null)
            c.setEndereco(new Endereco());
        if(pesquisaBairroList.getSelectedValue() == bairroTF.getText()){
            c.getEndereco().setBairro(bairrosList.get(pesquisaBairroList.getSelectedIndex()));
            
        }else{
            Bairro bairroTemp = new Bairro();
            bairroTemp.setNome(bairroTF.getText());
            bairroTemp.setId(new BairroDao().buscarExistente(bairroTemp));
            
            if(bairroTemp.getId() != null)
                c.getEndereco().setBairro(new BairroDao().localizarPorId(bairroTemp.getId()));
            else{
                c.getEndereco().setBairro(bairroTemp);
                c.getEndereco().getBairro().setTaxa(0F);
                
            }
        c.getEndereco().getBairro().setId(new BairroDao().salvar(c.getEndereco().getBairro()));    
        
        c.getEndereco().setRua(ruaTF.getText());
        c.getEndereco().setNumero(numeroTF.getText());
        c.getEndereco().setComplemento(complementoTF.getText());
        
        c.getEndereco().setId(new EnderecoDao().salvar(c.getEndereco()));
        
        c.setNome(nomeTF.getText());
        c.setDDD(dddTF.getText());
        c.setTelefone(telefoneTF.getText());
        
        c.setId(new ClienteDao().salvar(c));
        
        
        buscar(buscarTF.getText());
     }
    }//GEN-LAST:event_atualizarBTNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(jList1.getSelectedValue() != null){
            Cliente c = clientes.get(jList1.getSelectedIndex());
            new ClienteDao().excluirCliente(c);
            
                
            buscar(buscarTF.getText());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void telefoneTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneTFKeyTyped
        String caracteresDisponiveis = "0123456789";

        if (!caracteresDisponiveis.contains(evt.getKeyChar() + "") || telefoneTF.getText().length() >= 9) 
            evt.consume();
    }//GEN-LAST:event_telefoneTFKeyTyped

    private void dddTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dddTFKeyTyped
        String caracteresDisponiveis = "0123456789";

        if (!caracteresDisponiveis.contains(evt.getKeyChar() + "") || dddTF.getText().length() >= 2) 
            evt.consume();
    }//GEN-LAST:event_dddTFKeyTyped

    private void limparBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBTNActionPerformed
        jList1.clearSelection();
        atualizarBTN.setText("Salvar");
        limparCampos();
        buscar();
    }//GEN-LAST:event_limparBTNActionPerformed

    private void pesquisaBairroListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaBairroListMouseExited
        pesquisaBairroList.setVisible(false);
    }//GEN-LAST:event_pesquisaBairroListMouseExited

    private void pesquisaBairroListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaBairroListMousePressed
        if(pesquisaBairroList.getSelectedValue() != null){
            bairroTF.setText(bairrosList.get(pesquisaBairroList.getSelectedIndex()).getNome());
            pesquisaBairroList.setVisible(false);

        }
    }//GEN-LAST:event_pesquisaBairroListMousePressed

    private void bairroTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroTFActionPerformed

    private void bairroTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bairroTFKeyTyped

        String text = bairroTF.getText();
        char evtText = evt.getKeyChar();
        if (evtText != '\b' && evtText != '\n') {
            text = text + evtText;
        }
        DefaultListModel model = new DefaultListModel();
        bairrosList = new BairroDao().buscarPorNome(text);
        bairrosList.forEach(b -> {
            model.addElement(b.getNome());
        });

        pesquisaBairroList.setVisible(true);
        pesquisaBairroList.setModel(model);
        if (text.length() == 0 || bairrosList.size() == 0) {
            pesquisaBairroList.setVisible(false);
        }

        if(bairrosList.size() == 1 && (bairrosList.get(0).getNome() == null ? text == null : bairrosList.get(0).getNome().equals(text))){
            pesquisaBairroList.setSelectedIndex(0);

        }
    }//GEN-LAST:event_bairroTFKeyTyped
// </editor-fold>  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBTN;
    private javax.swing.JTextField bairroTF;
    private javax.swing.JTextField buscarTF;
    private javax.swing.JTextField complementoTF;
    private javax.swing.JTextField dddTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparBTN;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JTextField numeroTF;
    private javax.swing.JList<String> pesquisaBairroList;
    private javax.swing.JTextField ruaTF;
    private javax.swing.JTextField telefoneTF;
    // End of variables declaration//GEN-END:variables
}
